config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy', as: :logout

  resource :user, only: :destroy do
    get 'retire'
  end

  resources :events, except: :index do
    resources :tickets, only: [:new, :create, :destroy]
  end
  match '*path' => 'application#error404', via: :all
end

app/models/event.rb
# -*- coding: utf-8 -*-
class Event < ActiveRecord::Base
  mount_uploader :event_image, EventImageUploader

  has_many :tickets, dependent: :destroy
  belongs_to :owner, class_name: 'User'

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  validate :start_time_should_be_before_end_time

  def created_by?(user)
    return false unless user
    owner_id == user.id
  end

  def self.ransackable_attributes(auth_object = nil)
    %w(name start_time)
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  private

  def start_time_should_be_before_end_time
    return unless start_time && end_time

    if start_time >= end_time
      errors.add(:start_time, 'は終了時間よりも前に設定してください')
    end
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

app/models/user.rb
# -*- coding: utf-8 -*-
class User < ActiveRecord::Base
  before_destroy :check_all_events_finished

  has_many :created_events, class_name: 'Event', foreign_key: :owner_id, dependent: :nullify
  has_many :tickets, dependent: :nullify
  has_many :participating_events, through: :tickets, source: :event

  def self.find_or_create_from_auth_hash(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
  end

  private

  def check_all_events_finished
    now = Time.zone.now
    if created_events.where(':now < end_time', now: now).exists?
      errors[:base] << '公開中の未終了イベントが存在します。'
    end

    if participating_events.where(':now < end_time', now: now).exists?
      errors[:base] << '未終了の参加イベントが存在します。'
    end
    errors.blank?
  end
end

app/controllers/application_controller.rb
# -*- coding: utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  rescue_from Exception, with: :error500
  rescue_from ActiveRecord::RecordNotFound, ActionController::RoutingError, with: :error404

  def error404
    render 'error404', status: 404, formats: [:html]
  end

  def error500(e)
    logger.error [e, *e.backtrace].join("\n")
    render 'error500', status: 500, formats: [:html]
  end

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/events_controller.rb
# -*- coding: utf-8 -*-
class EventsController < ApplicationController
  before_action :authenticate, except: :show

  def show
    @event = Event.find(params[:id])
    @ticket = current_user && current_user.tickets.find_by(event_id: params[:id])
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: '作成しました'
    else
      render :new
    end
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private

  def event_params
    params.require(:event).permit(
      :name, :place, :event_image, :event_image_cache,
      :remove_event_image, :content, :start_time, :end_time
    )
  end
end

app/controllers/sessions_controller.rb
# -*- coding: utf-8 -*-
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end

  def failure
    redirect_to root_url, alert: "ログインに失敗しました"
  end
end

app/controllers/tickets_controller.rb
# -*- coding: utf-8 -*-
class TicketsController < ApplicationController
  before_action :authenticate

  def new
    raise ActionController::RoutingError, 'ログイン状態で TicketsController#new にアクセス'
  end

  def create
    ticket = current_user.tickets.build do |t|
      t.event_id = params[:event_id]
      t.comment = params[:ticket][:comment]
    end
    if ticket.save
      flash[:notice] = 'このイベントに参加表明しました'
      head 201
    else
      render json: { messages: ticket.errors.full_messages }, status: 422
    end
  end

  def destroy
    ticket = current_user.tickets.find_by!(event_id: params[:event_id])
    ticket.destroy!
    redirect_to event_path(params[:event_id]), notice: 'このイベントの参加をキャンセルしました'
  end
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController
  before_action :authenticate

  def retire
  end

  def destroy
    if current_user.destroy
      reset_session
      redirect_to root_path, notice: '退会完了しました'
    else
      render :retire
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  PER = 10

  def index
    @q = Event.page(params[:page]).per(PER).order(:start_time).search(search_params)

    @events = @q.result(distinct: true)
  end

  private

  def search_params
    params.require(:q).permit!
  rescue
    { start_time_gteq: Time.zone.now }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_for_twitter(user)
    "https://twitter.com/#{user.nickname}"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/error404.html.erb
ご指定になったページは存在しません

app/views/application/error500.html.erb
エラーが発生しました

app/views/events/edit.html.erb
<% now = Time.zone.now %>

<div class="page-header">
  <h1>イベント情報編集</h1>
</div>

<%= form_for(@event, class: 'form-horizontal', role: 'form') do |f| %>
  <% if @event.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: 'form-control' %>
  </div>
  <div class="form-group">
    <% if @event.event_image? %>
      <div class="thumbnail">
        <%= image_tag @event.event_image.url %>
      </div>
    <% end %>
    <%= f.file_field :event_image %>
    <%= f.hidden_field :event_image_cache %>
  </div>
  <% if @event.event_image? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :remove_event_image %>
        画像を削除する
      </label>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :start_time %>
    <div>
      <%= f.datetime_select :start_time, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_time %>
    <div>
      <%= f.datetime_select :end_time, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', row: 10 %>
  </div>

  <%= f.submit '更新', class: 'btn btn-default', data: { disable_with: '更新中…' } %>
<% end %>

app/views/events/new.html.erb
<% now = Time.zone.now %>

<div class="page-header">
  <h1>イベント作成</h1>
</div>

<%= form_for(@event, class: 'form-horizontal', role: 'form', html: { multipart: true }) do |f| %>
  <% if @event.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: 'form-control' %>
  </div>
  <div class="form-group">
    <% if @event.event_image? %>
      <div class="thumbnail">
        <%= image_tag @event.event_image.url %>
      </div>
    <% end %>
    <%= f.file_field :event_image %>
    <%= f.hidden_field :event_image_cache %>
  </div>
  <div class="form-group">
    <%= f.label :start_time %>
    <div>
      <%= f.datetime_select :start_time, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_time %>
    <div>
      <%= f.datetime_select :end_time, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', row: 10 %>
  </div>

  <%= f.submit '作成', class: 'btn btn-default', data: { disable_with: '作成中…' } %>
<% end %>

app/views/events/show.html.erb
<div class="page-header">
  <h1>
    <%= @event.name %>
  </h1>
</div>
<div class="row">
  <div class="col-md-8">
    <% if @event.event_image? %>
      <div class="thumbnail">
        <%= image_tag @event.event_image.url %>
      </div>
    <% end %>
    <div class="panel panel-default">
      <div class="panel-heading">
        主催者
      </div>
      <div class="panel-body">
        <% if @event.owner %>
          <%= link_to(url_for_twitter(@event.owner)) do %>
            <%= image_tag @event.owner.image_url %>
            <%= "@#{@event.owner.nickname}" %>
          <% end %>
        <% else %>
          退会したユーザです
        <% end %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        開催時間
      </div>
      <div class="panel-body">
        <%= @event.start_time.strftime('%Y/%m/%d %H:%M') %> - <%= @event.end_time.strftime('%Y/%m/%d %H:%M') %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        開催場所
      </div>
      <div class="panel-body">
        <%= @event.place %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        イベント内容
      </div>
      <div class="panel-body">
        <%= @event.content %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <% if @event.created_by?(current_user) %>
      <%= link_to 'イベントを編集する', edit_event_path(@event), class: 'btn btn-info btn-lg btn-block' %>
      <%= link_to 'イベントを削除する', event_path(@event), class: 'btn btn-danger btn-lg btn-block', method: :delete, data: { confirm: '本当に削除しますか？' } %>
    <% end %>
    <% if @ticket %>
      <%= link_to '参加をキャンセルする', event_ticket_path(@event, @ticket), method: :delete, class: 'btn btn-warning btn-lg btn-block' %>
    <% elsif logged_in? %>
      <button class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#createTicket">
        参加する
      </button>
      <div class="modal fade" id="createTicket" tabindex="-1" role="dialog" aria-labelledby="dialogHeader" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="dialogHeader">参加コメント</h4>
            </div>
            <%= form_for(@event.tickets.build, url: event_tickets_path(@event), remote: true) do |f| %>
              <div class="modal-body">
                <%= f.text_field :comment, class: 'form-control' %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
                <%= f.button '送信', class: 'btn btn-primary', data: { disable_with: '送信中…' } %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <%= link_to '参加する', new_event_ticket_path(@event), class: "btn btn-primary btn-lg btn-block" %>
    <% end %>
    <hr>
    <div class="panel panel-default">
      <div class="panel-heading">
        参加者
      </div>
      <div class="panel-body">
        <ul class="list-unstyled">
          <% @tickets.each do |ticket| %>
            <% if ticket.user %>
              <li>
                <%= link_to(url_for_twitter(ticket.user)) do %>
                  <%= image_tag ticket.user.image_url, width: 20, height: 20 %>
                  <%= "@#{ticket.user.nickname}" %>
                <% end %>
                <%= ticket.comment %>
              </li>
            <% else %>
              退会したユーザです
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeEvents</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'AwesomeEvents', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'イベントを作る', new_event_path %></li>
            <% if logged_in? %>
              <li><%= link_to '退会', retire_user_path %></li>
              <li><%= link_to 'ログアウト', logout_path %></li>
            <% else %>
              <li><%= link_to 'Twitterでログイン', '/auth/twitter' %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/retire.html.erb
<div class="page-header">
  <h1>退会の確認</h1>
</div>
<% if current_user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% current_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>退会した場合、ユーザに関するデータが全て削除されます。</p>
<p>ただし、以下の場合は退会できません。</p>
<ul>
  <li>
    公開中の未終了イベントがある場合
  </li>
  <li>
    未終了の参加イベントがある場合
  </li>
</ul>
<hr>
<%= link_to '退会する', user_path, method: :delete, class: 'btn btn-danger' %>

app/views/welcome/index.html.erb
<% now = Time.zone.now %>
<div class="page-header">
  <h1>イベント一覧</h1>
</div>
<%= search_form_for(@q, url: root_path, class: 'well') do |f| %>
  <div class="form-group">
    <%= f.label :name_cont, 'イベント名' %>
    <%= f.text_field :name_cont, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :start_time_gteq, '開催日' %>
    <div>
      <%= f.date_select :start_time_gteq, start_year: now.year, end_year: now.year + 1, prompt: true  %>〜
    </div>
  </div>
  <%= f.submit '検索', class: 'btn btn-default' %>
<% end %>
<div class="list-group">
  <% @events.each do |event| %>
    <%= link_to(event, class: 'list-group-item') do %>
      <h4 class="list-group-item-heading">
        <%= event.name %>
      </h4>
      <p class="list-group-item-text">
        <%= event.start_time.strftime('%Y/%m/%d %H:%M') %> - <%= event.end_time.strftime('%Y/%m/%d %H:%M') %>
      </p>
    <% end %>
  <% end %>
  <%= paginate @events %>
</div>